### ISSUE TITLE
Package compatilibity

### ISSUE THREAD

**Issue by ToddyTheNoobDud** [ybd-project/ytdl-core#16]
So im making an fork of [@distube/youtube](https://www.npmjs.com/package/toddys-youtube), Which use this project as the ytdl main code, to make youtube work normally again

I wish to get some help from the owners, like after 5.1.1 the validateURL function + createAgent  stopped working. What alternatives i can use for that? (for my package, i used GetBasicInfo function, to make it work again)

And an feature request would be: Add an auto save poToken for an .txt or something, and after restarts or something it can be re-added again, wasting less time

**Comment by ybd-project** [comment]
Thank you very much. We will implement this in the next version.
Regarding ValidateURL+createAgent, can you provide specific code?

**Comment by ToddyTheNoobDud** [comment]
Forgot to mention, but if you try to use @distube/soundcloud, It always returns 'Not an youtube domain', so soundcloud cannot be used with this

**Comment by ybd-project** [comment]
Is there an error in the validateUrl function?
It is working in my environment.

**Comment by ybd-project** [comment]
Has the problem been resolved?
If I do not receive a reply for a day, I will close this issue.

**Comment by ybd-project** [comment]
I am closing this issue because a day has passed since the above post. If you have any more questions, please create a new issue. Thank you.
