### ISSUE TITLE
How to stream audioonly?

### ISSUE THREAD

**Issue by orewafuad** [ybd-project/ytdl-core#18]
## Describe the feature

How can I get audio-only streaming using this package?

**Comment by ybd-project** [comment]
Thanks for the ish. I am currently creating a new example as `Stream` in the example folder. Please wait.
We will let you know when it is completed.

**Comment by ybd-project** [comment]
https://github.com/ybd-project/ytdl-core/blob/main/examples/Stream/src/audio/streamMp3.js
Please refer to this.

**Comment by orewafuad** [comment]
Oke, I'll give that a try. Thanks for the help!

**Comment by ybd-project** [comment]
If you have any questions, send them here.

**Comment by orewafuad** [comment]
Is it for streaming or downloading?

**Comment by ybd-project** [comment]
For download. Maybe an example of stream response?

**Comment by orewafuad** [comment]
Yes, it's directly for streaming only.

**Comment by ybd-project** [comment]
I understand. Rename the one you just created to the download folder and create a new one as a new streamResponse.
Do you want to use express?

**Comment by orewafuad** [comment]
Yes, I am using Express.

**Comment by ybd-project** [comment]
> Yes, I am using Express.

ok

**Comment by orewafuad** [comment]
do you have an example for that?

**Comment by ybd-project** [comment]
I am creating it now. Possibly tomorrow, but as much as possible.

**Comment by orewafuad** [comment]
Thank you, I really appreciate that!

**Comment by ybd-project** [comment]
We are done, see the StreamResponse in the example folder.

**Comment by ybd-project** [comment]
I understand. We will release v5.1.3 tomorrow, so I will fix it there.

**Comment by ybd-project** [comment]
v5.1.3 has been released. Please check to see if the problem has been fixed.

**Comment by orewafuad** [comment]
Wow, it's working, bro! Thanks a lot!

**Comment by ybd-project** [comment]
This issue has been resolved and will be closed.

**Comment by orewafuad** [comment]
![Screenshot_80](https://github.com/user-attachments/assets/938021be-907e-460b-821e-ba75add509cc)
Hi, I have another question. How can I get the URL like in the image?

**Comment by ybd-project** [comment]
Use the `getFullInfo` function to get information about the entire video. Pass it to the `downloadFromInfo` function.
You can retrieve it from the information (`formats`) retrieved from the `getFullInfo` function.
Alternatively, you can implement the following to obtain only the format to be downloaded.
```ts
import { YtdlCore } from '@ybd-project/ytdl-core';
const ytdl = new YtdlCore();

//                                                ↓ this
ytdl.download("URL").on('info', console.log).pipe(PIPE);
```
