### ISSUE TITLE
What measures should be taken for its continuous operation (Question)

### ISSUE THREAD

**Issue by yourshaxzod** [ybd-project/ytdl-core#2]
Thank you very much for creating this, I have a question, I want to create an api that receives video data from youtube and uploads the video, what should I pay attention to for it to work continuously, can I use IP rotation or Proxy server? ? and it would be helpful if you could share any successful methods you have tried.

**Comment by ybd-project** [comment]
For continuous operation, it is important to limit the number of requests from the same IP.
If an IP is blocked, it is effective to wait until it is unblocked.

**Comment by yourshaxzod** [comment]
> For continuous operation, it is important to limit the number of requests from the same IP. If an IP is blocked, it is effective to wait until it is unblocked.

can i get uptime without any ip routing and proxy servers? or can it be done by ip routing?

**Comment by ybd-project** [comment]
Yes. Continued operation is possible without proxies, etc., if nothing else.

**Comment by yourshaxzod** [comment]
> Yes. Continued operation is possible without proxies, etc., if nothing else.

Thanks for your help
