### ISSUE TITLE
EROFS: read-only file system, mkdir '/var/task/<directory>/CacheFiles

### ISSUE THREAD

**Issue by omenocal** [ybd-project/ytdl-core#20]
## Describe the bug
When updating the package to the latest version v5.1.2 and deploying to AWS Lambda, the function cannot even start because of this Cache error.

## Error Details (Log)
```json
{
    "errorType": "Error",
    "errorMessage": "EROFS: read-only file system, mkdir '/var/task/<directory>/CacheFiles'",
    "code": "EROFS",
    "errno": -30,
    "syscall": "mkdir",
    "path": "/var/task/<directory>/CacheFiles",
    "stack": [
        "Error: EROFS: read-only file system, mkdir '/var/task/<directory>/CacheFiles'",
        "    at Object.mkdirSync (node:fs:1372:26)",
        "    at 40963 (/var/task/<directory>/index.js:73469:23)",
        "    at __webpack_require__ (/var/task/<directory>/index.js:308982:42)",
        "    at 13868 (/var/task/<directory>/index.js:73623:17)",
        "    at __webpack_require__ (/var/task/<directory>/index.js:308982:42)",
        "    at 57530 (/var/task/<directory>/index.js:74312:19)",
        "    at __webpack_require__ (/var/task/<directory>/index.js:308982:42)",
        "    at 62811 (/var/task/<directory>/index.js:72929:16)",
        "    at __webpack_require__ (/var/task/<directory>/index.js:308982:42)",
        "    at 50218 (/var/task/<directory>/index.js:2109:5)"
    ]
}
```

## Environment

- Video URL: any URL
- @ybd-project/ytdl-core version: 5.1.2
- Node.js version: 20
- Operating system: AWS Lambda

**Comment by ybd-project** [comment]
Thank you, please wait for the release as we will add an option to disable the file cache in v5.1.3.

**Comment by ybd-project** [comment]
v5.1.3 has been released. Please check to see if the problem has been fixed.

**Comment by omenocal** [comment]
It worked, thanks for your hard work on this. As a suggestion for a future release. I understand the importance of the cache in this logic. Maybe we can take advantage of the /tmp/ folder in Lambda. We're allowed to write to that folder. And we can verify if the code is actually running in a lambda function by checking one of the default env variables of the lambda runtime.



![Screenshot 2024-09-12 at 7 08 08 AM](https://github.com/user-attachments/assets/8c1ee0b6-5d86-4870-b372-7dd2fd6bf539)
![Screenshot 2024-09-12 at 7 08 08 AM](https://github.com/user-attachments/assets/8c1ee0b6-5d86-4870-b372-7dd2fd6bf539)

**Comment by ybd-project** [comment]
Thank you. This will be used as a reference for future development.
