### ISSUE TITLE
Problem with successful retrieval of information but download fails with 403

### ISSUE THREAD

**Issue by ybd-project** [ybd-project/ytdl-core#21]
## Describe the bug
Retrieving video information from YouTube is successful, but downloading fails with status code 403.

## Error Details (Log)
Please refer to https://github.com/ybd-project/ytdl-core/discussions/13#discussioncomment-10594751

![image](https://github.com/user-attachments/assets/eb4e4c20-0c41-4dd6-a99b-58c09fa673cc)

## Environment

- Video URL: Any URL
- @ybd-project/ytdl-core version: latest
- Node.js version: Unknown
- Operating system: Unknown

**Comment by VenomSA** [comment]
Happens to me too, getting 403 since yesterday.

**Comment by ybd-project** [comment]
Maybe the following methods may be useful.

1. set the UserAgent to the request. (Currently no explicitly valid value is set.)
2. Add a `pot` parameter to the URL. I heard somewhere that you can add a PoToken to the `pot` parameter.

If these are valid, they will be implemented in a new version.

**Comment by nikitafloy** [comment]
> Maybe the following methods may be useful.
> 
> 1. set the UserAgent to the request. (Currently no explicitly valid value is set.)
> 2. Add a `pot` parameter to the URL. I heard somewhere that you can add a PoToken to the `pot` parameter.
> 
> If these are valid, they will be implemented in a new version.

tried, still not working

**Comment by ybd-project** [comment]
I really don't know under what circumstances the 403 is occurring...

**Comment by nikitafloy** [comment]
> I really don't know under what circumstances the 403 is occurring...
> 
> Also, does the 403 occur on all client URLs? So far we have confirmed the occurrence with the web client and WebCreator

ios working good, other is not

**Comment by ybd-project** [comment]
> > I really don't know under what circumstances the 403 is occurring...
> > 
> > Also, does the 403 occur on all client URLs? So far we have confirmed the occurrence with the web client and WebCreator
> 
> ios working good, other is not

Thanks for the valuable information, I will update the 403 error to select the IOS client.

**Comment by ybd-project** [comment]
Version v5.1.6, which addresses this issue, is now available. Please try it to see if it is fixed.

**Comment by VenomSA** [comment]
> Version v5.1.6, which addresses this issue, is now available. Please try it to see if it is fixed.

Still not working..

[ web ]: The URL for the video did not return a successful response. Got another format.
Reason: Status code: 403
 [  DEBUG  ]: [ ios ]: The URL for the video did not return a successful response. Got another format.

**Comment by ybd-project** [comment]
If you get this far, it is most likely an IP restriction.
If there is no reason, try specifying the option `filter: "audioandvideo"`. videos with an itag of 18 may work.

**Comment by ybd-project** [comment]
Also, does the problem occur at all URLs?

**Comment by nikitafloy** [comment]
@VenomSA and check your DNS and firewall settings. 

I used to have no problem connecting to sources and getting information through node.js, but I spent 2 days to solve the problem with accessing google. 

This problem is not solved in any of the ytdl packages and forks.

**Comment by VenomSA** [comment]
> If you get this far, it is most likely an IP restriction. If there is no reason, try specifying the option `filter: "audioandvideo"`. videos with an itag of 18 may work.

I have like 20 proxies, how could that happen so sudden? I managed to got this working when we last talked - in the issue i opened couple days ago and then it stopped suddenly. 

I also tried with "audioandvideo" and it doesn't want to work.

**Comment by VenomSA** [comment]
> @VenomSA and check your DNS and firewall settings.
> 
> I used to have no problem connecting to sources and getting information through node.js, but I spent 2 days to solve the problem with accessing google.
> 
> This problem is not solved in any of the ytdl packages and forks.

What do you mean accessing google? Im trying to access an youtube video (audio only)

**Comment by MOXHARTZ** [comment]
Hi, the 403 error is not related to ytdl. It shows that we are directly banned by youtube.

When I try to watch videos from youtube, google server does not return the 200 response. I can search, fetch informations but i can't get the video source from google servers. So I am blacklisted. Probably it's the same for other people who have this problem. 

Maybe youtube's ban can be bypassable with oauth. I will update here if I try with a new ip

**Comment by ybd-project** [comment]
Good news everyone, there is a possibility to bypass this 403 by implementing a proxy in Cloudflare Workers. We are currently planning a v5.1.7 release for this. Please wait.

**Comment by ybd-project** [comment]
May I assume that this problem has been solved by the implementation of the proxy?

One concern now is that we just received a phishing report from CloudFlare.
![スクリーンショット 2024-09-18 205728](https://github.com/user-attachments/assets/072765c9-5f82-4137-9e60-c066103197ae)

**Comment by MOXHARTZ** [comment]
The proxy doesn't seem to be working either

![Screenshot 2024-09-18 164137](https://github.com/user-attachments/assets/da0a695e-5cd8-40e1-8954-24b6e25e9b8b)

```
const OPTIONS = {
    // filter: 'audioonly',
    // chunking: true,
    // format: 'lowest',
    originalProxyUrl: 'https://{{domain}}.workers.dev',
}
const ytdl = new YtdlCore({
        poToken: poToken,
        visitorData: visitorData,
        // oauth2: NORMAL_OAUTH2,
        ...OPTIONS
    })
    const info = await ytdl.getBasicInfo(url)
    if (!info) return false;
    const details = info?.videoDetails
    const seconds = details?.lengthSeconds
    if (!seconds) return false;
    if (+seconds > 900) {
        blockedUrls[url] = 'Video is longer than 15 minutes'
        return 'duration'
    }
    const data = ytdl.download(url, {
        // filteringClients: ["tvEmbedded"],
    })
    ```

**Comment by MOXHARTZ** [comment]
Same

![image](https://github.com/user-attachments/assets/bc73e13c-28e0-4f1c-93f4-b1f3f70cce33)

**Comment by ybd-project** [comment]
It works fine on my end with that proxy, so I don't know what is causing it.
At the moment it could be due to the fact that it is processed near the end user.
