### ISSUE TITLE
Getting RequestError: 401 while using OAuth

### ISSUE THREAD

**Issue by Tanish2409** [ybd-project/ytdl-core#22]
## Describe the bug
I have setup everything exactly as specified in the basic example, but I get `401` error while using `oauth` with credentials generated from `cobalt`. If I don't use `oauth` then everything is working fine.

## Code
`accessToken` and `refreshToken` are generated using `cobalt`

```ts
import { YtdlCore } from '@ybd-project/ytdl-core';

const NORMAL_OAUTH2 = new YtdlCore.OAuth2({
	accessToken: process.env.GOOGLE_OAUTH2_ACCESS_TOKEN as string,
	refreshToken: process.env.GOOGLE_OAUTH2_REFRESH_TOKEN as string,
	expiryDate: process.env.GOOGLE_OAUTH2_EXPIRY_DATE as string,
});

const ytdl = new YtdlCore({
	oauth2: NORMAL_OAUTH2,
});

ytdl
  .getBasicInfo(youtubeLink)
  .then((info) => {
    console.log(info);
  })
  .catch((err) => {
    console.error('🚀 ~ err ~ : ', err);
  });
```

## Error Details (Log)
```bash
[  INFO!  ]: Since PoToken and VisitorData are not specified, they are generated automatically.
[  DEBUG  ]: To speed up processing, html5Player and signatureTimestamp are pre-fetched and cached.
Server is running on port 3000
[ SUCCESS ]: Successfully generated a poToken.

RequestError: Status Code: 401
    at Function.request (/Users/tanish/dev/server/yt_2_mp3/node_modules/@ybd-project/ytdl-core/src/core/Fetcher.ts:31:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/tanish/dev/server/yt_2_mp3/node_modules/@ybd-project/ytdl-core/src/core/clients/Base.ts:46:28 {
  statusCode: 401
}
```

## Environment

- Video URL: `https://www.youtube.com/watch?v=IPYTxAHeR_o`
- @ybd-project/ytdl-core version: `^5.1.4-2`
- Node.js version: `v20.17.0`
- Operating system: `macOs`

**Comment by ybd-project** [comment]
Thank you for your report.
We will investigate this issue.

**Comment by Tanish2409** [comment]
it's `2024-09-15T05:42:43.119Z`

**Comment by ybd-project** [comment]
> @ybd-project it's `2024-09-15T05:42:43.119Z`

Thank you.

**Comment by ybd-project** [comment]
The results of the survey suggest the following factors
1. the `refreshToken` or `accessToken` is not copied correctly or is most likely incorrect. Please generate them again and make sure they are copied properly.
2. the IP may be banned.

**Comment by Tanish2409** [comment]
@ybd-project Thanks, I generated the new credentials and then it was working fine.

**Comment by ybd-project** [comment]
This issue has been resolved and will be closed.
