### ISSUE TITLE
Stable method of getting PoToken and VisitorData (automatic)

### ISSUE THREAD

**Issue by ybd-project** [ybd-project/ytdl-core#6]
## Details
`@ybd-project/ytdl-core` allows the specification of `PoToken` and `VisitorData`. But the only way to get these is as follows.

1. open the video embed page (/embed/)
2. play the video and monitor the request
3. get `PoToken` and `VisitorData` from the body of the request to /youtubei/v1/player

It is very difficult to do these things within ytdl-core and will degrade performance.
Therefore, I would like to discussion here the automatic acquisition of `PoToken` and `VisitorData`.

**Comment by ybd-project** [comment]
Update: [YunzheZJU/youtube-po-token-generator](https://github.com/YunzheZJU/youtube-po-token-generator) is the most promising so far.

**Comment by yourshaxzod** [comment]
> Yangilanish: [YunzheZJU/youtube-po-token-generator](https://github.com/YunzheZJU/youtube-po-token-generator) hozirgacha eng istiqbolli hisoblanadi.

Is there a better solution using oauth or is there any bugs with this method?

**Comment by ybd-project** [comment]
> Is there a better solution using oauth or is there any bugs with this method?

There is also a way to use OAuth, but it is unclear whether this can be implemented in ytdl-core, so this will be investigated.

**Comment by ybd-project** [comment]
> There is also a way to use OAuth, but it is unclear whether this can be implemented in ytdl-core, so this will be investigated.

After researching, we may be able to implement this by referring to LuanRT/YouTube.js.
LuanRT/YouTube.js has very good implementation examples and can be based on them.
(Do not import YouTube.js internally due to stability and performance issues.)

**Comment by ybd-project** [comment]
This issue is expected to be resolved and has been closed.
