### ISSUE TITLE
 Error: All player APIs responded with an error. (Clients: web_creator, ios, android)

### ISSUE THREAD

**Issue by sslexus** [ybd-project/ytdl-core#7]
## Describe the bug
Thanks for the fork!

I encountered a strange error using poToken & visitorData approach like so :
```ts
    const videoID = "1oFQamxoFy0";
    const poToken = "...";
    const visitorData = "..."


    const info = await ytdl.getInfo(videoID, { poToken, visitorData });

    // Filter for audio formats
    const audioFormats = ytdl.filterFormats(info.formats, "audioonly");
    const format = ytdl.chooseFormat(audioFormats, { quality: "highestaudio" });

    // Create a PassThrough stream to capture the audio data
    const audioStream = new PassThrough();

    // Pipe the audio stream to the PassThrough stream
    ytdl
      .downloadFromInfo(info, { format, poToken, visitorData })
      .pipe(audioStream);
```

Here's the thing: I ran this in a REST endpoint, and it works locally. But once deployed (Vercel), not anymore. What would you suggest me here?

## Error Details (Log)
```
 Error: All player APIs responded with an error. (Clients: web_creator, ios, android)
```

## Environment

- Video URL:  https://www.youtube.com/watch?v=1oFQamxoFy0
- @ybd-project/ytdl-core version: 5.0.12
- Node.js version: 20.11.1 (Vercel)
- Operating system: Unix (Vercel serverless)

**Comment by ybd-project** [comment]
Thank you for presenting the issue.
You can specify clients as the second argument of the getInfo function, so try specifying `['web_creator', 'tv_embedded']` there.
```typescript
ytdl.getInfo(VIDEO_URL, {
    poToken: 'PO_TOKEN',
    visitorData: 'VISITOR_DATA',
    clients: ['web_creator', 'tv_embedded']
});
```

If this does not work, it is recommended to generate the poToken again.

**Comment by ybd-project** [comment]
Is the problem resolved?
